"""
This type stub file was generated by pyright.
"""

import sys
import os
import importlib
import types
from pkgutil import extend_path
from . import _gi
from ._gi import PyGIDeprecationWarning, PyGIWarning, Repository, _API as _API

__path__ = ...
_static_binding_error = ...
if "gobject" in sys.modules: ...
_versions = ...
_overridesdir = ...
_gobject = ...
version_info = ...
__version__ = ...
_options = ...

class OverrideImport:
    def __init__(self, overrides_path) -> None: ...
    def find_spec(self, fullname, path, target=...) -> None: ...

_pgi_overrides_path = ...
if _pgi_overrides_path: ...

class _DummyStaticModule(types.ModuleType):
    __path__ = ...
    def __getattr__(self, name): ...

def check_version(version) -> None: ...
def require_version(namespace, version) -> None:
    """Ensures the correct versions are loaded when importing `gi` modules.

    :param namespace: The name of module to require.
    :type namespace: str
    :param version: The version of module to require.
    :type version: str
    :raises ValueError: If module/version is already loaded, already required, or unavailable.

    :Example:

    .. code-block:: python

        import gi

        gi.require_version("Gtk", "3.0")

    """
    ...

def require_versions(requires) -> None:
    """Utility function for consolidating multiple `gi.require_version()` calls.

    :param requires: The names and versions of modules to require.
    :type requires: dict

    :Example:

    .. code-block:: python

        import gi

        gi.require_versions({"Gtk": "3.0", "GLib": "2.0", "Gio": "2.0"})
    """
    ...

def get_required_version(namespace) -> None: ...
def require_foreign(namespace, symbol=...) -> None:
    """Ensure the given foreign marshaling module is available and loaded.

    :param str namespace:
        Introspection namespace of the foreign module (e.g. "cairo")
    :param symbol:
        Optional symbol typename to ensure a converter exists.
    :type symbol: str or None
    :raises: ImportError

    :Example:

    .. code-block:: python

        import gi
        import cairo

        gi.require_foreign("cairo")

    """
    ...

def get_option(name) -> bool | None:
    """Get option by name.

    :param str name:
        Name of the option.
    """
    ...

def disable_legacy_autoinit() -> None:
    """Disable the legacy initialization of Gdk and Gtk.

    These modules are automatically initialized on import from `gi.repository`.
    This is not required, and was only kept for backwards compatibility reason.
    This behavior may eventually be dropped for future Gtk major releases.

    Usually, users should not manually perform these initializations but let
    e.g. `Gtk.Application` manage it when needed.
    """
    ...
