"""
This type stub file was generated by pyright.
"""

import enum

class GEnumMeta(enum.EnumMeta):
    def __new__(metacls, name, bases, classdict, /, **kwargs):  # -> Self:
        ...
    @property
    def __enum_values__(self):  # -> dict[Any, GEnumMeta]:
        ...

class GEnum(enum.IntEnum, metaclass=GEnumMeta):
    __module__ = ...
    __gtype__ = ...

class GFlagsMeta(enum.EnumMeta):
    def __new__(metacls, name, bases, classdict, /, **kwargs):  # -> Self:
        ...
    @property
    def __flags_values__(self):  # -> dict[Any, GFlagsMeta]:
        ...

class GFlags(enum.IntFlag, metaclass=GFlagsMeta):
    __module__ = ...
    __gtype__ = ...
