"""
This type stub file was generated by pyright.
"""

import typing
from typing_extensions import Self

if typing.TYPE_CHECKING: ...

class GError(RuntimeError):
    message: str
    domain: str
    code: int
    def __init__(
        self, message: str = ..., domain: str = ..., code: int = ...
    ) -> None: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def copy(self) -> Self: ...
    def matches(self, domain: str | int, code: int) -> bool:
        """Placeholder that will be monkey patched in GLib overrides."""
        ...

    @staticmethod
    def new_literal(domain: int, message: str, code: int) -> Self:
        """Placeholder that will be monkey patched in GLib overrides."""
        ...
