"""
This type stub file was generated by pyright.
"""

from gi.repository import GObject

def define_builder_scope():  # -> type[BuilderScope]:
    class BuilderScope(GObject.GObject, Gtk.BuilderScope): ...

def connect_func(
    builder, obj, signal_name, handler_name, connect_object, flags, cls
):  # -> None:
    ...
def register_template(cls):  # -> None:
    ...
def init_template(self, cls, base_init_template):  # -> None:
    ...

class Child:
    def __init__(self, name=..., **kwargs) -> None: ...

class CallThing:
    def __init__(self, name, func) -> None: ...

class Callback:
    def __init__(self, name=...) -> None: ...
    def __call__(self, func):  # -> CallThing:
        ...

def validate_resource_path(path):  # -> None:
    """Raises GLib.Error in case the resource doesn't exist."""
    ...

class Template:
    def __init__(self, **kwargs) -> None: ...
    @classmethod
    def from_file(cls, filename):  # -> Self:
        ...
    @classmethod
    def from_string(cls, string):  # -> Self:
        ...
    @classmethod
    def from_resource(cls, resource_path):  # -> Self:
        ...

    Callback = Callback
    Child = Child
    def __call__(self, cls):  # -> type:
        ...

__all__ = ["Template"]
