"""
This type stub file was generated by pyright.
"""

import signal
from contextlib import contextmanager

def ensure_socket_not_inheritable(sock):  # -> None:
    """Ensures that the socket is not inherited by child processes.

    Raises:
        EnvironmentError
        NotImplementedError: With Python <3.4 on Windows

    """
    ...

_wakeup_fd_is_active = ...

@contextmanager
def wakeup_on_signal():  # -> Generator[None, Any, None]:
    """A decorator for functions which create a glib event loop to keep
    Python signal handlers working while the event loop is idling.

    In case an OS signal is received will wake the default event loop up
    shortly so that any registered Python signal handlers registered through
    signal.signal() can run.

    In case the wrapped function is not called from the main thread it will be
    called as is and it will not wake up the default loop for signals.
    """
    ...

PyOS_getsig = ...
PyOS_setsig = ...
if signal.getsignal(signal.SIGINT) is signal.default_int_handler:
    startup_sigint_ptr = ...
else:
    startup_sigint_ptr = ...

def sigint_handler_is_default():  # -> Literal[False]:
    """Returns if on SIGINT the default Python handler would be called."""
    ...

@contextmanager
def sigint_handler_set_and_restore_default(handler):  # -> Generator[None, Any, None]:
    """Context manager for saving/restoring the SIGINT handler default state.

    Will only restore the default handler again if the handler is not changed
    while the context is active.
    """
    ...

def is_main_thread():  # -> bool:
    """Returns True in case the function is called from the main thread."""
    ...

_callback_stack = ...
_sigint_called = ...

@contextmanager
def register_sigint_fallback(callback):  # -> Generator[None, Any, None]:
    """Installs a SIGINT signal handler in case the default Python one is
    active which calls 'callback' in case the signal occurs.

    Only does something if called from the main thread.

    In case of nested context managers the signal handler will be only
    installed once and the callbacks will be called in the reverse order
    of their registration.

    The old signal handler will be restored in case no signal handler is
    registered while the context is active.
    """
    ...

class DummyEventLoop:
    @classmethod
    @contextmanager
    def paused(cls):  # -> Generator[None, Any, None]:
        ...
    @classmethod
    @contextmanager
    def running(cls, quit_func):  # -> Generator[None, Any, None]:
        ...

def get_event_loop(ctx):  # -> GLibEventLoop | type[DummyEventLoop]:
    """Return the correct GLibEventLoop or a dummy that just registers the
    signal wakeup mechanism.
    """
    ...
