"""
This type stub file was generated by pyright.
"""

G_MAXFLOAT = ...
G_MAXDOUBLE = ...
G_MININT = ...
G_MAXINT = ...
G_MAXUINT = ...
G_MINLONG = ...
G_MAXLONG = ...
G_MAXULONG = ...

class Property:
    """Creates a new Property which when used in conjunction with
    GObject subclass will create a Python property accessor for the
    GObject ParamSpec.

    :param callable getter:
        getter to get the value of the property
    :param callable setter:
        setter to set the value of the property
    :param type type:
        type of property
    :param default:
        default value, must match the property type.
    :param str nick:
        short description
    :param str blurb:
        long description
    :param GObject.ParamFlags flags:
        parameter flags
    :keyword minimum:
        minimum allowed value (int, float, long only)
    :keyword maximum:
        maximum allowed value (int, float, long only)

    .. code-block:: python

        class MyObject(GObject.Object):
            prop = GObject.Property(type=str)


        obj = MyObject()
        obj.prop = "value"

        obj.prop  # now is 'value'

    The API is similar to the builtin :py:func:`property`:

    .. code-block:: python

        class AnotherObject(GObject.Object):
            value = 0

            @GObject.Property
            def prop(self):
                "Read only property."
                return 1

            @GObject.Property(type=int)
            def propInt(self):
                "Read-write integer property."
                return self.value

            @propInt.setter
            def propInt(self, value):
                self.value = value
    """

    _type_from_pytype_lookup = ...
    _min_value_lookup = ...
    _max_value_lookup = ...
    _default_lookup = ...
    class __metaclass__(type):
        def __repr__(self):  # -> Literal['<class \'GObject.Property\'>']:
            ...

    def __init__(
        self,
        getter=...,
        setter=...,
        type=...,
        default=...,
        nick=...,
        blurb=...,
        flags=...,
        minimum=...,
        maximum=...,
    ) -> None: ...
    def __repr__(self):  # -> str:
        ...
    def __get__(self, instance, klass):  # -> Self:
        ...
    def __set__(self, instance, value):  # -> None:
        ...
    def __call__(self, fget):  # -> Self:
        """Allows application of the getter along with init arguments."""
        ...

    def getter(self, fget):  # -> Self:
        """Set the getter function to fget. For use as a decorator."""
        ...

    def setter(self, fset):  # -> Self:
        """Set the setter function to fset. For use as a decorator."""
        ...

    def get_pspec_args(
        self,
    ):  # -> tuple[Any | type, str, str | Any, *tuple[Any | int | str | float | None, ...], Any]:
        ...

def install_properties(cls):  # -> None:
    """Scans the given class for instances of Property and merges them
    into the classes __gproperties__ dict if it exists or adds it if not.
    """
    ...
