"""
This type stub file was generated by pyright.
"""

class Signal(str):
    """Object which gives a nice API for creating and binding signals.

    :param name:
        Name of signal or callable closure when used as a decorator.
    :type name: str or callable
    :param callable func:
        Callable closure method.
    :param GObject.SignalFlags flags:
        Flags specifying when to run closure.
    :param type return_type:
        Return type of the Signal.
    :param list arg_types:
        List of argument types specifying the signals function signature
    :param str doc:
        Documentation of signal object.
    :param callable accumulator:
        Accumulator method with the signature:
        func(ihint, return_accu, handler_return, accu_data) -> boolean
    :param object accu_data:
        User data passed to the accumulator.

    :Example:

    .. code-block:: python

        class Spam(GObject.Object):
            velocity = 0

            @GObject.Signal
            def pushed(self):
                self.velocity += 1

            @GObject.Signal(flags=GObject.SignalFlags.RUN_LAST)
            def pulled(self):
                self.velocity -= 1

            stomped = GObject.Signal('stomped', arg_types=(int,))

            @GObject.Signal
            def annotated_signal(self, a:int, b:str):
                "Python3 annotation support for parameter types.

        def on_pushed(obj):
            print(obj)

        spam = Spam()
        spam.pushed.connect(on_pushed)
        spam.pushed.emit()
    """
    class BoundSignal(str):
        """Temporary binding object which can be used for connecting signals
        without specifying the signal name string to connect.
        """
        def __new__(cls, name, *args, **kargs):  # -> Self:
            ...
        def __init__(self, signal, gobj) -> None: ...
        def __repr__(self):  # -> str:
            ...
        def __call__(self, *args, **kargs):
            """Call the signals closure."""
            ...

        def connect(self, callback, *args, **kargs):
            """Same as GObject.Object.connect except there is no need to specify
            the signal name.
            """
            ...

        def connect_detailed(self, callback, detail, *args, **kargs):
            """Same as GObject.Object.connect except there is no need to specify
            the signal name. In addition concats "::<detail>" to the signal name
            when connecting; for use with notifications like "notify" when a property
            changes.
            """
            ...

        def disconnect(self, handler_id):  # -> None:
            """Same as GObject.Object.disconnect."""
            ...

        def emit(self, *args, **kargs):
            """Same as GObject.Object.emit except there is no need to specify
            the signal name.
            """
            ...

    def __new__(cls, name=..., *args, **kargs):  # -> Self:
        ...
    def __init__(
        self,
        name=...,
        func=...,
        flags=...,
        return_type=...,
        arg_types=...,
        doc=...,
        accumulator=...,
        accu_data=...,
    ) -> None: ...
    def __get__(self, instance, owner=...):  # -> Self | BoundSignal:
        """Returns a BoundSignal when accessed on an object instance."""
        ...

    def __call__(self, obj, *args, **kargs):  # -> Self | None:
        """Allows for instantiated Signals to be used as a decorator or calling
        of the underlying signal method.
        """
        ...

    def copy(self, newName=...):  # -> Self:
        """Returns a renamed copy of the Signal."""
        ...

    def get_signal_args(
        self,
    ):  # -> tuple[Any, Any | None, tuple[()] | tuple[Any, ...] | Any, Any | None, Any | None]:
        """Returns a tuple of: (flags, return_type, arg_types, accumulator, accu_data)."""
        ...

class SignalOverride(Signal):
    """Specialized sub-class of Signal which can be used as a decorator for overriding
    existing signals on GObjects.

    :Example:

    .. code-block:: python

        class MyWidget(Gtk.Widget):
            @GObject.SignalOverride
            def configure_event(self):
                pass
    """
    def get_signal_args(self):  # -> Literal['override']:
        """Returns the string 'override'."""
        ...

def get_signal_annotations(func):  # -> tuple[Any | None, tuple[Any, ...] | tuple[()]]:
    """Attempt pulling python 3 function annotations off of 'func' for
    use as a signals type information. Returns an ordered nested tuple
    of (return_type, (arg_type1, arg_type2, ...)). If the given function
    does not have annotations then (None, tuple()) is returned.
    """
    ...

def install_signals(cls):  # -> None:
    """Adds Signal instances on a GObject derived class into the '__gsignals__'
    dictionary to be picked up and registered as real GObject signals.
    """
    ...
