"""
This type stub file was generated by pyright.
"""

_generate_doc_string_func = ...

def set_doc_string_generator(func):  # -> None:
    """Set doc string generator function.

    :param callable func:
        Callable which takes a GIInfoStruct and returns documentation for it.
    """
    ...

def get_doc_string_generator():  # -> None:
    """Returns the currently registered doc string generator."""
    ...

def generate_doc_string(info):
    """Generate a doc string given a GIInfoStruct.

    :param gi.types.BaseInfo info:
        GI info instance to generate documentation for.
    :returns:
        Generated documentation as a string.
    :rtype: str

    This passes the info struct to the currently registered doc string
    generator and returns the result.
    """
    ...

_type_tag_to_py_type = ...
