"""
This type stub file was generated by pyright.
"""

import sys
import asyncio
import selectors
from collections.abc import Mapping
from contextlib import contextmanager
from gi.repository import GLib

__all__ = ["GLibEventLoop", "GLibEventLoopPolicy"]
g_main_loop_run = ...

class _IdleSource(GLib.Source):
    """Internal helper source for idle task handling

    The only advantage is that we can keep the source around.
    """
    def __init__(self, loop) -> None: ...
    def prepare(
        self,
    ):  # -> tuple[Literal[False], Literal[-1]] | tuple[bool, Literal[-1]]:
        ...
    def check(self):  # -> bool:
        ...
    def dispatch(self, callback, args): ...

class GLibTask(asyncio.Task):
    """This is a simple asyncio.Task subclass that will be returned when using the
    GLibEventLoop. It adds functionality to set the priority that is used to
    iterate the task's coroutine.
    """
    def __init__(self, *args, **kwargs) -> None: ...
    def set_priority(self, priority):  # -> None:
        """Set the GLib priority used to iterate the task's coroutine"""
        ...

    def get_priority(self, priority):  # -> int:
        """Get the GLib priority used to iterate the task's coroutine"""
        ...

class _GLibEventLoopMixin:
    """Base functionally required for both proactor and selector.

    The proactor/selector is always available through _selector, and we assume
    it has the following extra functionality that we provide:
     * _source: the GSource subclass
     * _dispatching: boolean whether it is dispatching currently
     * attach/detach: add/remove the GSource from the main context

    In principle, we simply override run_forever to call into GLib, with the
    assumption that a GSource is registered which will then call back into
    the python mainloop _run_once handler when needed. This in turn calls
    self._selector.select(), which means we just need to make sure to return
    our already prepared events at that point.

    If no main_context is passed, then the current default main context will
    be used when available. If the thread does not yet have any main context
    set, then a main context will be created.

    When creating an event loop like this, it should be used as a context
    manager. This ensure that the main context is set for the thread, that
    GLib routines will properly iterate the EventLoop and that no second
    EventLoop for the same main context is created by accident.
    """
    def __init__(self, main_context) -> None: ...
    @contextmanager
    def paused(self):  # -> Generator[None, Any, None]:
        """This context manager ensures the EventLoop is *not* being iterated.

        It purely exists to handle the case where python code iterates the main
        context more gracefully.
        """
        ...

    @contextmanager
    def running(self, quit_func):  # -> Generator[None, Any, None]:
        """This context manager ensures the EventLoop is marked as running
        while other API is iterating its main context.
        The passed quit function is used to stop all recursion levels when
        stop() is called.
        """
        ...

    def time(self): ...
    def stop(self):  # -> None:
        ...
    def __repr__(self):  # -> str:
        ...
    def __enter__(self):  # -> None:
        ...
    def __exit__(self, exc_type, exc_value, traceback):  # -> None:
        ...

class _GLibEventLoopRunMixin:
    def run_forever(self):  # -> None:
        ...

class _SourceBase(GLib.Source):
    """Common Source functionality for both unix and win32"""
    def __init__(self, selector) -> None: ...
    def dispatch(self, callback, args): ...

class _SelectorMixin:
    """A Mixin for common functionality of the Selector and Proactor."""
    def __init__(self, context, loop) -> None: ...
    def close(self):  # -> None:
        ...
    def select(self, timeout=...):  # -> list[Any]:
        ...

if sys.platform != "win32":
    class GLibEventLoop(
        _GLibEventLoopMixin, _GLibEventLoopRunMixin, asyncio.SelectorEventLoop
    ):
        """An asyncio event loop that runs the python mainloop inside GLib.

        Based on the asyncio.SelectorEventLoop
        """

        _GLIB_SIGNALS = ...
        def __init__(self, main_context=...) -> None: ...
        def add_signal_handler(self, sig, callback, *args):  # -> None:
            """Add a handler for UNIX signal"""
            ...

        def remove_signal_handler(self, sig):  # -> bool:
            ...
        def close(self):  # -> None:
            ...

    class _Source(_SourceBase):
        def prepare(self):  # -> tuple[Literal[False], Any]:
            ...
        def check(self):  # -> bool:
            ...

    class _SelectorKey(selectors.SelectorKey): ...

    class _FileObjectMapping(Mapping):
        def __init__(self, fd_dict) -> None: ...
        def __len__(self):  # -> int:
            ...
        def get(self, fileobj, default=...): ...
        def __getitem__(self, fileobj): ...
        def __iter__(self): ...

    class _Selector(_SelectorMixin, selectors.BaseSelector):
        """A Selector for gi.events.GLibEventLoop registering python IO with GLib."""
        def __init__(self, context, loop) -> None: ...
        def attach(self):  # -> None:
            ...
        def detach(self):  # -> None:
            ...
        def register(self, fileobj, events, data=...):  # -> _SelectorKey:
            ...
        def unregister(self, fileobj): ...
        def get_key(self, fileobj): ...
        def get_map(self):  # -> _FileObjectMapping:
            """Return a mapping of file objects or file descriptors to
            selector keys.
            """
            ...

else:
    class _PushRunMixinBackMeta(type):
        def mro(cls):  # -> list[type]:
            ...

    class GLibEventLoop(
        _GLibEventLoopMixin,
        _GLibEventLoopRunMixin,
        asyncio.ProactorEventLoop,
        metaclass=_PushRunMixinBackMeta,
    ):
        """An asyncio event loop that runs the python mainloop inside GLib.

        Based on the asyncio.WindowsProactorEventLoopPolicy
        """
        def __init__(self, main_context=...) -> None: ...

    class _Source(_SourceBase):
        def __init__(self, proactor) -> None: ...
        def enable(self):  # -> None:
            ...
        def disable(self):  # -> None:
            ...
        def prepare(self):  # -> tuple[Literal[False], Literal[-1]] | tuple[bool, Any]:
            ...
        def check(self):  # -> bool:
            ...

    class _Proactor(_SelectorMixin, asyncio.IocpProactor):
        """A Proactor for gi.events.GLibEventLoop registering python IO with GLib."""
        def __init__(self, context, loop) -> None: ...
        def attach(self):  # -> None:
            ...
        def detach(self):  # -> None:
            ...

_set_event_loop_policy = ...
_get_event_loop_policy = ...

class GLibEventLoopPolicy(AbstractEventLoopPolicy):
    """An asyncio event loop policy that runs the GLib main loop.

    NOTE: Python 3.16 is removing the concept of the event loop policy.
    FIXME: say what to do in the future

    The policy allows creating a new EventLoop for threads other than the main
    thread. For the main thread, you can use get_event_loop() to retrieve the
    correct mainloop and run it.

    Note that, unlike GLib, python does not support running the EventLoop
    recursively. You should never iterate the GLib.MainContext from within
    the python EventLoop as doing so prevents asyncio events from being
    dispatched.

    As such, do not use API such as GLib.MainLoop.run or Gtk.Dialog.run.
    Instead use the proper asynchronous patterns to prevent entirely blocking
    asyncio.
    """

    _loops = ...
    _child_watcher = ...
    def __init__(self) -> None: ...
    def get_event_loop(self):  # -> None:
        """Get the event loop for the current context.

        Returns an event loop object for the thread default GLib.MainContext
        or in case of the main thread for the default GLib.MainContext.

        An exception will be thrown if there is no GLib.MainContext for the
        current thread. In that case, using new_event_loop() will create a new
        main context and main loop which can subsequently attached to the thread
        by calling set_event_loop().

        Returns a new GLibEventLoop or raises an exception.
        """
        ...

    def get_event_loop_for_context(self, ctx):  # -> None:
        """Get the event loop for a specific context."""
        ...

    def set_event_loop(self, loop):  # -> None:
        """Set the event loop for the current context (python thread) to loop.

        This is only permitted if the thread has no thread default main context
        with the main thread using the default main context.
        """
        ...

    def new_event_loop(self):  # -> GLibEventLoop:
        """Create and return a new event loop that iterates a new
        GLib.MainContext.
        """
        ...

    def __enter__(self):  # -> Self:
        ...
    def __exit__(self, exc_type, exc_value, traceback):  # -> Literal[False]:
        ...

    if sys.platform != "win32" and hasattr(
        AbstractEventLoopPolicy, "get_child_watcher"
    ):
        @classmethod
        def get_child_watcher(cls): ...
