"""
This type stub file was generated by pyright.
"""

repository = ...
modules = ...

def get_import_stacklevel(import_hook):  # -> Literal[4, 2, 8, 10]:
    """Returns the stacklevel value for warnings.warn() for when the warning
    gets emitted by an imported module, but the warning should point at the
    code doing the import.

    Pass import_hook=True if the warning gets generated by an import hook
    (warn() gets called in load_module(), see PEP302)
    """
    ...

class DynamicImporter:
    def __init__(self, path) -> None: ...
    def find_spec(self, fullname, path=..., target=...):  # -> None:
        ...
    def find_module(self, fullname, path=...):  # -> Self | None:
        ...
    def create_module(self, spec):  # -> IntrospectionModule | OverridesProxyModule:
        ...
    def exec_module(self, fullname):  # -> None:
        ...
