"""
This type stub file was generated by pyright.
"""

from types import ModuleType

repository = ...
_introspection_modules = ...

def get_parent_for_object(object_info):  # -> type[object] | Any:
    ...
def get_interfaces_for_object(object_info):  # -> list[Any]:
    ...

class IntrospectionModule(ModuleType):
    """An object which wraps an introspection typelib.

    This wrapping creates a python module like representation of the typelib
    using gi repository as a foundation. Accessing attributes of the module
    will dynamically pull them in and create wrappers for the members.
    These members are then cached on this introspection module.
    """
    def __init__(self, namespace, version=...) -> None:
        """Might raise gi._gi.RepositoryError."""
        ...

    def __getattr__(
        self, name
    ):  # -> type[__class_GObjectMeta] | type[__class_StructMeta]:
        ...
    def __repr__(self):  # -> str:
        ...
    def __dir__(self):  # -> list[str]:
        ...

def get_introspection_module(namespace):  # -> IntrospectionModule:
    """:Returns:
        An object directly wrapping the gi module without overrides.

    Might raise gi._gi.RepositoryError
    """
    ...

def get_platform_specific_module(namespace):  # -> ModuleType | None:
    """Return the platform-specific module for the given namespace, if available."""
    ...

def get_fallback_platform_specific_module_symbol(
    namespace, platform_namespace, symbol, prefix=...
):  # -> tuple[Any, str | Any]:
    """Return the original attribute and the wrapper attribute name for a
    platform-specific symbol fallback.
    """
    ...
