"""
This type stub file was generated by pyright.
"""

def snake_case(name):  # -> str:
    ...

class MetaClassHelper: ...

def find_vfunc_info_in_interface(bases, vfunc_name):  # -> None:
    ...
def find_vfunc_conflict_in_bases(vfunc, bases):  # -> None:
    ...

class _GObjectMetaBase(type):
    """Metaclass for automatically registering GObject classes."""
    def __new__(cls, name, bases, namespace, **kwargs):  # -> Self:
        ...
    def __init__(cls, name, bases, dict_) -> None: ...

class GObjectMeta(_GObjectMetaBase, MetaClassHelper):
    """Meta class used for GI GObject based types."""
    def __init__(cls, name, bases, dict_) -> None: ...
    def mro(cls):  # -> list[Any]:
        ...
    @property
    def __doc__(cls):  # -> Any | Literal[''] | None:
        """Meta class property which shows up on any class using this meta-class."""
        ...

def mro(C):  # -> list[Any]:
    """Compute the class precedence list (mro) according to C3, with GObject
    interface considerations.

    We override Python's MRO calculation to account for the fact that
    GObject classes are not affected by the diamond problem:
    http://en.wikipedia.org/wiki/Diamond_problem

    Based on http://www.python.org/download/releases/2.3/mro/
    """
    ...

def nothing(*args, **kwargs):  # -> None:
    ...

class StructMeta(type, MetaClassHelper):
    """Meta class used for GI Struct based types."""
    def __init__(cls, name, bases, dict_) -> None: ...
    @property
    def __doc__(cls):  # -> Literal['']:
        ...
