"""
This type stub file was generated by pyright.
"""

import functools
import types
import warnings
import importlib
import sys
from gi import PyGIDeprecationWarning
from gi._gi import CallableInfo, pygobject_new_full
from gi._constants import TYPE_INVALID, TYPE_NONE
from pkgutil import extend_path

__path__ = ...
_deprecated_attrs = ...

class OverridesProxyModule(types.ModuleType):
    """Wraps a introspection module and contains all overrides"""

    __slots__ = ...
    def __init__(self, introspection_module) -> None: ...
    def __getattr__(self, name):  # -> Any:
        ...
    def __delattr__(self, name):  # -> None:
        ...
    def __dir__(self):  # -> list[str]:
        ...
    def __repr__(self):  # -> str:
        ...

class _DeprecatedAttribute:
    """A deprecation descriptor for OverridesProxyModule subclasses.

    Emits a PyGIDeprecationWarning on every access and tries to act as a
    normal instance attribute (can be replaced and deleted).
    """
    def __init__(self, namespace, attr, value, replacement) -> None: ...
    def __get__(self, instance, owner):  # -> Any:
        ...
    def __set__(self, instance, value):  # -> None:
        ...
    def __delete__(self, instance):  # -> None:
        ...

def load_overrides(introspection_module):  # -> OverridesProxyModule:
    """Loads overrides for an introspection module.

    Either returns the same module again in case there are no overrides or a
    proxy module including overrides. Doesn't cache the result.
    """
    ...

def override(type_):  # -> Callable[..., Any]:
    """Decorator for registering an override.

    Other than objects added to __all__, these can get referenced in the same
    override module via the gi.repository module (get_parent_for_object() does
    for example), so they have to be added to the module immediately.
    """
    ...

overridefunc = ...

def deprecated(fn, replacement):  # -> _Wrapped[..., Any, ..., Any]:
    """Decorator for marking methods and classes as deprecated."""
    ...

def deprecated_attr(namespace, attr, replacement):  # -> None:
    """Marks a module level attribute as deprecated. Accessing it will emit
    a PyGIDeprecationWarning warning.

    e.g. for ``deprecated_attr("GObject", "STATUS_FOO", "GLib.Status.FOO")``
    accessing GObject.STATUS_FOO will emit:

        "GObject.STATUS_FOO is deprecated; use GLib.Status.FOO instead"

    :param str namespace:
        The namespace of the override this is called in.
    :param str namespace:
        The attribute name (which gets added to __all__).
    :param str replacement:
        The replacement text which will be included in the warning.
    """
    ...

def deprecated_init(
    super_init_func,
    arg_names,
    ignore=...,
    deprecated_aliases=...,
    deprecated_defaults=...,
    category=...,
    stacklevel=...,
):  # -> Callable[..., Any]:
    """Wrapper for deprecating GObject based __init__ methods which specify
    defaults already available or non-standard defaults.

    :param callable super_init_func:
        Initializer to wrap.
    :param list arg_names:
        Ordered argument name list.
    :param list ignore:
        List of argument names to ignore when calling the wrapped function.
        This is useful for function which take a non-standard keyword that is munged elsewhere.
    :param dict deprecated_aliases:
        Dictionary mapping a keyword alias to the actual g_object_newv keyword.
    :param dict deprecated_defaults:
        Dictionary of non-standard defaults that will be used when the
        keyword is not explicitly passed.
    :param Exception category:
        Exception category of the error.
    :param int stacklevel:
        Stack level for the deprecation passed on to warnings.warn
    :returns: Wrapped version of ``super_init_func`` which gives a deprecation
        warning when non-keyword args or aliases are used.
    :rtype: callable
    """
    ...

def strip_boolean_result(
    method, exc_type=..., exc_str=..., fail_ret=...
):  # -> _Wrapped[..., Any, ..., Any | None]:
    """Translate method's return value for stripping off success flag.

    There are a lot of methods which return a "success" boolean and have
    several out arguments. Translate such a method to return the out arguments
    on success and None on failure.
    """
    ...

def wrap_list_store_sort_func(func):  # -> Callable[..., Any]:
    ...
def wrap_list_store_equal_func(func):  # -> Callable[..., Any]:
    ...
